[general]
title = "Reporaft"
logo = ""
iconLogo = "tabler:license"

[general.seo]
name = "Reporaft"
description = "A directory for finding cool web app projects that are licensed with MIT License."
url = "https://reporaft.com"

[directory.data]
source = "json"  # default, mock, sheets, json
links = "outbound"
target = "_blank"

# [directory.data.sheets]
# key = "1BKVVFysQT8ZuPY8hUp--jwTrN-U20TrtML0idECIWmc"

# [directory.data.airtable]
# base = "base id"
# table = "Table Name"

[directory.search]
placeholder = "Search {0} MIT-licensed projects..."
showCount = true
icon = "tabler:search"

[directory.search.tags]
display = "show-all" # options: none,select,show-all
intersection = false

[directory.grid]
list = false
type = ""

[directory.grid.emptyState]
text = "No projects found matching your search."
type = "button"                                              # options: button, simple, link
icon = "tabler:exclamation-mark"

[directory.grid.card]
image = false
border = "shadow" # options: dashed, shadow, outline

[directory.grid.submit]
show = true
first = false
title = "Submit a Project"
description = "Share your MIT-licensed project with the community."
hideable = true

[directory.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "Featured ✨"

[directory.tagPages]
title = "{0} Projects"

[[directory.tags]]
key = "framework"
name = "Frameworks"
color = "slate"

[[directory.tags]]
key = "library"
name = "Libraries"
color = "zinc"

[[directory.tags]]
key = "javascript"
name = "JavaScript"
color = "yellow"

[[directory.tags]]
key = "python"
name = "Python"
color = "yellow"

[[directory.tags]]
key = "frontend"
name = "Frontend"
color = "blue"

[[directory.tags]]
key = "web"
name = "Web"
color = "indigo"

[header.banner]
show = false
text = "Follow mark_bruderer on twitter."
link = "https://x.com/intent/follow?screen_name=mark_bruderer"
brandText = "AI Agent Libraries"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Blog"
href = "/blog"

#[[header.navbar.links]]
#name = "Analytics"
#href = "https://us.posthog.com/shared/vHlGCcSqPjGH4r_QijaXSETtmN9J-g"
#target = "_blank"

[header.actionButton]
text = "Submit a Project"
href = "https://tally.so/r/mZQvk0"

[footer]
description = "Best directory for my niche."

[footer.socials.github]
link = ""
icon = "tabler:brand-github"

[footer.socials.facebook]
link = ""
icon = "tabler:brand-facebook"

[footer.socials.instagram]
link = ""
icon = "tabler:brand-instagram"

[footer.socials.x]
link = "https://x.com/mark_bruderer"
icon = "tabler:brand-twitter"

[footer.socials.youtube]
link = "https://www.youtube.com/@mark_hacks"
icon = "tabler:brand-youtube"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"
